# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog técnico de Rodrigo Valdés
email: rodrigovaldes@gmail.com
description: > # this means to ignore newlines until "baseurl":
 Este es mi sitio Blog en donde compartiré información respecto a mis descubrimientos
 técnicos. La idea es mostrar algunos de los proyectos en los cuales me encuentro 
 trabajando. Y asi poder demostrar aspectos técnicos de mi trabajo y mi pasión por 
 la tecnología.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: roxtrongo
github_username:  roxtrongo

# Build settings
markdown: kramdown
